export const SCREENS = {
  LOGIN: 'LOGIN',
  SIGN_UP: 'SIGN_UP',
  ENTER_CODE: 'ENTER_CODE',
  HOME: 'HOME',
  BOOKMARKS: 'BOOKMARKS',
  PROFILE: 'PROFILE',
  NOTIFICATIONS: 'NOTIFICATIONS',
  TABS: 'TABS',
  RECIPE: 'RECIPE',
  NON_TABS: 'NON_TABS',
} as const;
