export const SCREENS = {
  LOGIN: 'LOGIN',
  SIGN_UP: 'SIGN_UP',
  ENTER_CODE: 'ENTER_CODE',
  HOME: 'HOME',
  BOOKMARKS: 'BOOKMARKS',
  PROFILE: 'PROFILE',
  NOTIFICATIONS: 'NOTIFICATIONS',
} as const;
