export const SCREENS = {
  LOGIN: 'LOGIN',
  SIGN_UP: 'SIGN_UP',
  ENTER_CODE: 'ENTER_CODE',
  HOME: 'HOME',
  BOOKMARKS: 'BOOKMARKS',
  PROFILE: 'PROFILE',
  NOTIFICATIONS: 'NOTIFICATIONS',
  TABS: 'TABS',
  RECIPE: 'RECIPE',
  RECIPE_STACK: 'RECIPE_STACK',
  NON_TABS: 'NON_TABS',
  WRITE_REVIEW: 'WRITE_REVIEW',
} as const;
